import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/element/nav/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 z-10">
          <TopBar />
        </div>
        {children}
      </body>
    </html>
  );
}
